import type { StudioCommandMeta } from "../types";

export const COMMAND_CATALOG: StudioCommandMeta[] = [
  { id: "file.importDxf", label: "Import Drawing", category: "Home" },
  { id: "file.openProject", label: "Open Project", category: "Home", shortcut: "Ctrl+O" },
  { id: "file.save", label: "Save", category: "Home", shortcut: "Ctrl+S" },
  { id: "file.saveVersion", label: "Save Version", category: "Home" },
  { id: "file.newProject", label: "New Project", category: "Home" },
  { id: "export.fullPackage", label: "Export Package", category: "Home" },
  { id: "export.open", label: "Open Export Dialog", category: "Home" },
  { id: "detection.run", label: "Run Detection", category: "Detection", keywords: ["detect", "scan"] },
  { id: "detection.rerun", label: "Re-run Detection", category: "Detection" },
  { id: "detection.pickBoundary", label: "Pick Boundary", category: "Detection", keywords: ["scope", "boundary", "slab", "pick", "cad"] },
  { id: "detection.autoBoundary", label: "Auto Detect Boundary", category: "Detection", keywords: ["scope", "boundary", "auto", "slab"] },
  { id: "detection.drawSlabBoundary", label: "Draw Boundary", category: "Detection", keywords: ["scope", "boundary", "draw", "manual"] },
  { id: "detection.editBoundary", label: "Edit Boundary", category: "Detection", keywords: ["scope", "boundary", "edit", "vertex"] },
  { id: "detection.defineSlabBoundary", label: "Pick Boundary", category: "Detection", keywords: ["scope", "boundary", "slab"] },
  { id: "detection.applyBoundary", label: "Apply Boundary", category: "Detection", keywords: ["scope", "boundary", "apply", "clip"] },
  { id: "detection.seedRecovery", label: "Seed Recovery", category: "Detection" },
  { id: "polygon.drawManual", label: "Draw Polygon (Manual)", category: "Detection", keywords: ["manual", "draw", "polygon"] },
  { id: "zones.generate", label: "Generate Zones", category: "INT Zones", keywords: ["int", "zone"] },
  { id: "zones.rebuild", label: "Rebuild Zones", category: "INT Zones" },
  { id: "review.validate", label: "Run Validation", category: "Review" },
  { id: "review.mode", label: "Toggle Review Mode", category: "Review" },
  { id: "polygon.find", label: "Go to Polygon", category: "Review", shortcut: "Ctrl+G" },
  { id: "view.cadDrawing", label: "CAD Drawing", category: "View" },
  { id: "view.intZones", label: "INT Zones", category: "View" },
  { id: "view.faces", label: "Faces (Polygons)", category: "View" },
  { id: "view.obstacles", label: "Obstacles", category: "View" },
  { id: "view.boundary", label: "Boundary", category: "View" },
  { id: "view.labels", label: "Labels", category: "View" },
  { id: "view.goToCoordinates", label: "Go to Coordinates", category: "View" },
  { id: "view.fit", label: "Fit View", category: "View", shortcut: "F" },
  { id: "tool.select", label: "Select Tool", category: "Review", shortcut: "S" },
  { id: "tool.rectSelect", label: "Rectangle Select", category: "Review" },
  { id: "view.pan", label: "Pan Tool", category: "View", shortcut: "P" },
  { id: "edit.undo", label: "Undo", category: "Home", shortcut: "Ctrl+Z" },
  { id: "edit.redo", label: "Redo", category: "Home", shortcut: "Ctrl+Y" },
  { id: "palette.open", label: "Command Palette", category: "View", shortcut: "Ctrl+Shift+P" },
  { id: "layout.default", label: "Default Layout", category: "View" },
  { id: "layout.review", label: "Review Layout", category: "View" },
  { id: "layout.detection", label: "Detection Layout", category: "View" },
  {
    id: "help.exportPilotFeedback",
    label: "Export Pilot Feedback Template",
    category: "Help",
    keywords: ["feedback", "pilot", "template"],
  },
  { id: "help.shortcuts", label: "Keyboard Shortcuts", category: "Help" },
  { id: "help.about", label: "About", category: "Help" },
];
