import type { StudioCommandMeta } from "../types";

export const COMMAND_CATALOG: StudioCommandMeta[] = [
  { id: "file.openProject", label: "Open Drawing", category: "Home", shortcut: "Ctrl+O" },
  { id: "file.save", label: "Save", category: "Home", shortcut: "Ctrl+S" },
  { id: "file.saveVersion", label: "Save Version", category: "Home" },
  { id: "file.newProject", label: "New Project", category: "Home" },
  { id: "file.importDxf", label: "Import DXF", category: "Home" },
  { id: "detection.run", label: "Run Detection", category: "Detection", keywords: ["detect", "scan"] },
  { id: "detection.rerun", label: "Re-run Detection", category: "Detection" },
  { id: "detection.seedRecovery", label: "Seed Recovery", category: "Detection" },
  { id: "zones.generate", label: "Generate Zones", category: "INT Zones", keywords: ["int", "zone"] },
  { id: "zones.rebuild", label: "Rebuild Zones", category: "INT Zones" },
  { id: "review.validate", label: "Run Validation", category: "Review" },
  { id: "review.mode", label: "Toggle Review Mode", category: "Review" },
  { id: "export.open", label: "Open Export Dialog", category: "Home" },
  { id: "export.fullPackage", label: "Export Full Package", category: "Home" },
  { id: "polygon.find", label: "Go to Polygon", category: "Review", shortcut: "Ctrl+G" },
  { id: "view.goToCoordinates", label: "Go to Coordinates", category: "View" },
  { id: "view.fit", label: "Fit View", category: "View", shortcut: "F" },
  { id: "tool.select", label: "Select Tool", category: "Review", shortcut: "S" },
  { id: "tool.rectSelect", label: "Rectangle Select", category: "Review" },
  { id: "view.pan", label: "Pan Tool", category: "View", shortcut: "P" },
  { id: "edit.undo", label: "Undo", category: "Home", shortcut: "Ctrl+Z" },
  { id: "edit.redo", label: "Redo", category: "Home", shortcut: "Ctrl+Y" },
  { id: "palette.open", label: "Command Palette", category: "View", shortcut: "Ctrl+Shift+P" },
  { id: "layout.default", label: "Default Layout", category: "View" },
  { id: "layout.review", label: "Review Layout", category: "View" },
  { id: "layout.detection", label: "Detection Layout", category: "View" },
  { id: "help.shortcuts", label: "Keyboard Shortcuts", category: "View" },
  { id: "help.about", label: "About", category: "View" },
];
